version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile # Symfony with CLI installation
      args:
        USER_ID: 1000
        GROUP_ID: 1000
    container_name: symfony_app
    volumes:
      - ./app:/var/www/html
    environment:
      - APP_ENV=dev
      - DATABASE_URL=pgsql://test:test@symfony_postgres:5432/test
    networks:
      - symfony_network

  nginx:
    image: nginx:stable
    container_name: symfony_nginx
    ports:
      - "8081:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - symfony_network

  postgres:
    image: postgres:15
    container_name: symfony_postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - symfony_network

volumes:
  postgres_data:

networks:
  symfony_network:
